# -*- coding: utf-8 -*-
"""Build densify_payload for Cap. II §III Garissoles fourfold / actualis."""
from __future__ import annotations
import json
from pathlib import Path

OCR = Path(__file__).resolve().parent

LATIN = {
"166": """GAR. Observo deinde, nulla necessitate, vel magna utilitate, compulsum Virum Doctum, ut ita anxie et scrupulose subjectum in quatuor significata distingueret; cum quicunque hactenus de primi peccati imputatione locuti sunt, nihil aliud eo nomine intellexerint, ut ex ipsorum scriptis satis patere potest, quam ipsius primi hominis actualem illam transgressionem, qua Dei mandatum de non gustando fructu arboris interdictae violavit. Ut quid igitur opus erat per operosas ambages lectoris animum circumducere, et de peccato in nobis inhaerente, sive corruptione nostra originali, deque imputatione ac poena reatum ipsam consequente verba facere, de quibus in hac disputatione nequaquam agi satis notum est? Non enim quaeritur, utrum nobis omnibus insita sit corruptio, propter quam Deus poenas a nobis exigere merito possit, aut eam nobis imputare, quod nemo Evangelicorum unquam revocavit in dubium: Illud unum in Quaestionem hodie vocari quibusdam volupe est, utrum ex primo illo actuali Adae peccato aliquis reatus, et aliqua poenae dignitas posteris incumbat.""",

"167": """PLAC. Primum esto; nulla necessitate, vel magna utilitate compulsus peccatum Adae sic distinxerim, modo distinctio non sit falsa, nec noxia, nec prorsus inutilis, mihi satis est. Utinam in eius libro nihil minus verum, minus utile occurreret! Deinde verum non est, quod ait, quicunque de peccati Adae imputatione locuti sunt, eos nihil aliud eo nomine intellexisse, quam ipsius actualem transgressionem: cujus rei eum admonere debuerunt verba illa mea, ac ut verbis utar Calvini, quia intra nos est, quae, quia causae suae oberant, consulto omisit. Habentur autem illa Calvini verba Comm. in Rom. 5. vs. 17. integrum locum habes supra p. 92. Perit enim differentia quam illic observat inter Christum et Adamum, nisi peccatum Adae, quod nobis imputatur, intra nos sit, seque habeat ut qualitas nobis inhaerens. Tertio, Quod addit de peccato inhaerente ejusque imputatione in hac disputatione non agi, id ipsum dico hoc loco, ac ut dicerem distinctionem illam adhibui. Separandum enim fuit id quod non est inter nos controversum ab eo quod controversum est, removendaque ab hac quaestione omnis ambiguitas et confusio. Quo neglecto qui mihi in hac causa adversantur non me oppugnant, sed umbram suam. Denique quod dicit in quaestionem vocari, utrum ex primo illo actuali Adae peccato aliquis reatus et aliqua poenae dignitas posteris incumbat, vel falsum est, vel ad me non spectat: Doceo enim constanter ex illo peccato aliquem reatum et aliquam poenae dignitatem, si tamen dignitas appellanda est, posteris incumbere: tantum volo non immediate sed mediante corruptione quam peperit, incumbere.""",

"168": """GAR. Dicant vero, qui eam prae se ferunt in explicanda Quaestione diligentiam, annon ludificationi deputaturi sint, et praestigiarum loco habituri, si quis ex Novis illis Pontificiorum Doctoribus, qui pacificationis studio provincias et urbes obire credi volunt, blandulus accedat, et in causa momentosa, justificationis puta negocio, consensum cum Evangelicis profiteatur: se nimirum haud invito animo doctrinam amplecti de justificatione per imputatam Christi Domini nostri justitiam, dummodo distinctione adhibita rem explicare liceat; Quia scilicet justitia Christi variis modis accipi potest. 1. Pro actionibus illis ad legis divinae regulam exactissimis, quibus Christus et vivens et moriens plenissimum Patris sui mandatis obsequium praestitit. 2. Pro habituali illa et inhaerente justitia, qua Christi anima splendidissime enituit. 3. Pro justitia interna et habituali, qua unicuique fidelium subjective inest, sed quae justitia Christi merito dici possit, quoniam a Christo, Christique Spiritu, tanquam autore, in nos defluit. Hoc ergo ultimo sensu, agnoscere se, in controversia justificationis, imputationem justitiae Christi: at vero si prima et secunda significatione Christi justitiam accipiamus, se justitiae Christi imputationem nullam agnoscere, sed tanquam absurdam rejicere. Consensum certe in hoc negocio ita explicatum, nemo est, qui non conqueratur Ludibrium esse, potius quam consensum. &c.""",

"169": """PLAC. Hoc simile non est appositum, sed oppositum. Huic enim blandulo praestigiatori tam sum dissimilis quam album nigro. Primo ille se enumerasse prae se ferret omnes acceptiones justitiae Christi, cum tamen unam omitteret in justificationis negotio maxime momentosam, qua justitia Christi accipitur pro singulari illa obedientia quam praestitit patiendo mortem, mortem, inquam, crucis; quae vulgo justitia passiva appellatur, et imputari fidelibus ab omnibus Protestantibus sine dubitatione creditur, cum de imputatione justitiae activae, quam solam D. Gar. commemoravit, sit aliqua sententiarum discrepantia, quae pacem Ecclesiae non turbat. Ego vero primi Adae peccati acceptiones omnes recensui, nullam praetermisi. Secundo ille Christi justitiam eo sensu acceptam imputari diceret, quo sensu accepta imputari negatur constanter ab omnibus Protestantibus. Ego vero peccatum Adami eo sensu posteris imputari affirmavi, quo sensu iis imputari omnes Protestantes constanter tenent. Itaque ille consensum fingeret cum Evangelicis plane falsum: Quis enim unquam Evangelicorum docuit justitiam inhaerentem, quam habemus a Christo, nobis ad justificationem imputari? Quem autem ego profiteor consensum, is verus est, neque negatur, aut negari potest a quoquam non Pelagiano.""",

"170": """Tertio denique; Ille prae se ferret tertiam illam justitiae Christi acceptionem pro justitia nobis inhaerente, esse eam, quae intelligitur, cum quaeritur, utrum justitia Christi nobis imputetur, necne? Id quod falsum est. Opponitur enim justitia Christi in ea quaestione nostrae justitiae nobis insitae. Ego vero contra istas acceptiones peccati Adamici, quibus illud imputari dixi consensum esse, removi a statu quaestionis inter nos agitandae, et quidem disertissimis verbis. Quare ab omni ludificatione alienissimus fui.""",
}

TITLES = {
"166": "Man. Post. Cap. II §III: Garissoles — fourfold needless; only actualis transgressio meant",
"167": "Man. Post. Cap. II §III: Placeus — distinction not false; Calvin quia intra nos; reatus mediate",
"168": "Man. Post. Cap. II §III: Garissoles — Pontificiorum ludification analogy (threefold justitia Christi)",
"169": "Man. Post. Cap. II §III: Placeus — analogy opposite; passive justice omitted; false consensus",
"170": "Man. Post. Cap. II §III: Placeus — third acceptio not the question; alienissimus; before §XIV",
}

PASS_A = {
"166": "GAR. I observe next, that by no necessity, or great utility, the Learned Man was compelled so anxiously and scrupulously to distinguish the subject into four significations; since whoever hitherto have spoken of the imputation of the first sin, have understood nothing else by that name, as can sufficiently appear from their writings, than that actual transgression of the first man himself, by which he violated Gods command concerning not tasting the fruit of the forbidden tree. Why then was it needful through laborious windings to lead the readers mind around, and to make words about sin inhering in us, or our original corruption, and about imputation and the penalty following the guilt itself, concerning which it is sufficiently known that they are by no means treated in this disputation? For it is not asked whether corruption is implanted in us all, on account of which God may deservedly exact penalties from us, or impute it to us, which no one of the Evangelicals ever called back into doubt: That one thing it is delightful to certain ones to call today into Question, whether from that first actual sin of Adam some guilt, and some worthiness of penalty, lies upon the posterity.",
"167": "PLAC. First let it be; by no necessity, or great utility, I was compelled so to distinguish Adams sin, provided the distinction is not false, nor harmful, nor wholly useless, it is enough for me. Would that in his book nothing less true, less useful occurred! Next it is not true, what he says, that whoever have spoken of the imputation of Adams sin understood nothing else by that name than his actual transgression: of which thing those words of mine ought to have admonished him, and as I use Calvins words, because it is within us, which, because they obstructed his cause, he deliberately omitted. But those words of Calvin are held Comm. on Rom. 5 vs. 17